title: Onur Arıkan
author:
  name: Onur Arıkan
  email: onur93arikan@gmail.com
description: > # this means to ignore newlines until "show_excerpts:" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
  In this web page, I share my personal journey in Computer Science as well as the handy tips that make my life easier while using the web, command line applications or generally everything that I can explore in my computer.
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://opethef10.github.io"

minima:
  skin: dark
  date_format: "%-d %b %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/opethef10" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/onur93arikan" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

permalink: /:title/

rss: rss

google_analytics: G-ZLFYTWQ4QR

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: onur93arikan

kramdown:
  input: GFM
  syntax_highlighter: rouge
    

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: other
  - scope:
      path: ''
      type: post_tags
    values:
      permalink: "/tags/:name/"
      layout: tag

collections:
  post_tags:
    permalink: /tags/:name/
    output: true

